server:
  port: 18080
  servlet:
    context-path: /universeOfGames
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/universe
    password: root
    username: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
    format:
      date: yyyy/MM/dd
  jackson:
    date-format: yyyy/MM/dd
mybatis:
  type-aliases-package: com.universe.sjl.entity
  mapper-locations: classpath:mapper/*Mapper.xml
